# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - my-expensesapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b2861f989f044fd19368701c47fedc0b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4cd02d9be7404846947fd8c0c5f98080 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b2861f989f044fd19368701c47fedc0b }}/fabiocosta89/my-expenses:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'my-expensesapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cb7818d3d52548b98c9f902fbb8afb14 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b2861f989f044fd19368701c47fedc0b }}/fabiocosta89/my-expenses:${{ github.sha }}'